configuration: Release
  
build:
  project: CacheHelper.sln
  verbosity: minimal
  publish_nuget: true
branches:
  # whitelist
  only:
    - master
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.0"
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: "1.0.0-alpha"