configuration: Release
  
build:
  project: CacheHelper.sln
  verbosity: minimal
  publish_nuget: true
branches:
  # whitelist
  only:
    - master
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
